- name: "Installing Flatpak"
  community.general.pacman:
    name:
      - flatpak
  become: true
  tags: flatpak

- name: "Installing Flatpak packages"
  kewlfft.aur.aur:
    name: "{{ item }}"
  loop: "{{ flatpak_pkgs }}"
  tags: flatpak
