- name: "Installing Swaync packages"
  kewlfft.aur.aur:
    name: "{{ item }}"
  loop:
    - swaync

- name: Creating config directory if it doesn't exist
  ansible.builtin.file:
    path: "{{config_dir}}/swaync"
    state: directory
    mode: '0755'

- name: Copying config files
  ansible.builtin.command:
    cmd: stow -d {{stow_dir}} -t {{home}} --no-folding --dotfiles -S swaync
  changed_when: true
