- name: "Installing Rofi package"
  community.general.pacman:
    name:
      - rofi

- name: Create rofi config dir
  ansible.builtin.file:
    path: "{{config_dir}}/rofi"
    state: directory
    mode: '0755'

- name: Copying Rofi configuration
  ansible.builtin.command:
    cmd: stow -d {{root_dir}}/../ -t {{home}} --no-folding --dotfiles -S rofi
