- name: "Installing Rofi package"
  community.general.pacman:
    name:
      - rofi
  become: true
  tags: rofi

- name: Create rofi config dir
  ansible.builtin.file:
    path: "{{config_dir}}/rofi"
    state: directory
    mode: '0755'
  tags: rofi

- name: Copying Rofi configuration
  ansible.builtin.command:
    cmd: stow -d {{stow_dir}} -t {{home}} --no-folding --dotfiles -S rofi
  changed_when: true
  tags: rofi
