# Move the directory to the second line
#format = '$all$directory$character'
scan_timeout = 50
add_newline = false
right_format = """$time"""

[character]
success_symbol = "[ïƒ¬](bold green) "
error_symbol = "[ïƒ¬](bold red) "

[line_break]
#disabled = true

[directory]
#fish_style_pwd_dir_length = 1

[status]
#symbol = "ðŸ”´"
format = '[\[$symbol $common_meaning$signal_name$maybe_int $status\]]($style) '
#format = '[\[$symbol $status\]]($style) '
map_symbol = true
disabled = false

[time]
disabled = false
#time_format = "%R" # Hour:Minute Format
format = '[ ó°¥” $time ]($style)'

[username]
style_user = "bold green"
#show_always = true

[hostname]
style = 'bold green'
#ssh_only = false
format = '[$ssh_symbol$hostname]($style) [::](bold red) '


[git_branch]
format = '\([$symbol$branch(:$remote_branch)]($style)\) '

[os]
disabled = false
style = 'bold cyan'

[os.symbols]
Arch = "ó°£‡ "

