- name: "Installing Terminal Emulator packages"
  community.general.pacman:
    name:
      - alacritty
  tags: alacritty
  become: true

- name: Create Alacritty config dir
  ansible.builtin.file:
    path: "{{config_dir}}/alacritty"
    state: directory
    mode: '0755'
  tags: alacritty

- name: Copying Alacrity configuration
  ansible.builtin.command:
    cmd: stow -d {{stow_dir}} -t {{home}} --no-folding --dotfiles -S alacritty
  register: ala_output
  changed_when: ala_output.rc != 0
  tags: alacritty
