- name: "Installing Terminal Emulator packages"
  community.general.pacman:
    name:
      - alacritty

- name: Create Alacritty config dir
  ansible.builtin.file:
    path: "{{config_dir}}/alacritty"
    state: directory
    mode: '0755'

- name: Copying Alacrity configuration
  ansible.builtin.command:
    cmd: stow -d {{root_dir}}/../ -t {{home}} --no-folding --dotfiles -S alacritty
