- name: "AUR | Test if paru is already installed"
  shell: command -v paru
  register: paru_exist
  ignore_errors: true
  become: false
  changed_when: false

- name: "AUR | Installing Remaining packages"
  ansible.builtin.expect:
    command: paru -S --noprogressbar --noconfirm --needed {{item}}
    responses: 
      password: "{{sudo_password}}"
  # WE can install informant later
  when: paru_exist is succeeded
  with_items:
    - sddm-conf-git
    - distro-grub-themes-arch
    - lssecret-git
    - menulibre
    - colloid-cursors-git
    - numix-circle-icon-theme-git
    - plymouth-theme-arch-logo-new
    - sddm-eucalyptus-drop
    - ttf-ms-fonts
    - tty-clock
  become: false
