- name: "Installing Sway packages"
  kewlfft.aur.aur:
    name: "{{ item }}"
  loop: "{{(sway_pkgs.values() + wayland_common_pkgs.values()) | flatten }}"

- name: Creating config directory if it doesn't exist
  ansible.builtin.file:
    path: "{{config_dir}}/sway"
    state: directory
    mode: '0755'

- name: Copying config files
  ansible.builtin.command:
    cmd: stow -d {{stow_dir}} -t {{home}} --no-folding --dotfiles -S sway
  changed_when: true
