---
dependencies:
  - role: hyprland
  - role: waybar
  - role: swaync
  - role: swappy
  - role: alacritty
  - role: tmux
  - role: rofi
  - role: zsh
  - role: neovim
  - role: sddm
  - role: yazi
  - role: zathura
  - role: git
  - role: mpd
  - role: webbrowser
  - role: fastfetch
