home: "{{ ansible_facts['user_dir'] }}"
config_dir: "{{home}}/.config"
script_dir: "{{home}}/Scripts"

root_dir: "{{playbook_dir}}"
stow_dir: "{{root_dir}}/../"

themes_path:
  - /usr/share/themes
  - "{{home}}/.local/share/themes"
icons_path:
  - /usr/share/icons
  - "{{home}}/.local/share/icons"

is_amdgpu: "Advanced Micro Devices, Inc. [AMD/ATI]"
is_nvidia: "NVIDIA Corporation"
is_intel: GenuineIntel
is_amd: AuthenticAMD

default_apps:
  terminal:
    - alacritty
  filemanager:
    - thunar
  browser:
    - brave

wayland_common_pkgs:
  main:
    - swaybg # Background setter
    - swww # animations
    - imv # Image Viewer
    - nwg-look # Theme picker
    - nwg-displays # Display settings
    - nwg-drawer # Big menu
    - nwg-icon-picker # Icon picker
    - wl-clipboard # Clipboard
    - cliphist # Clipboard manager
    - wf-recorder # Screen recorder
    - slurp # Selection area
    - grim # Screenshotter
    - wlsunset # Gamma adjuster
    - xdg-desktop-portal-gtk
    - desktop-file-utils
    - wev
  aur:
    - waypaper # Background setter
    - wvkbd
   # - wallust-git

os_intgpu:
  - intel-media-driver

os_essential:
  - archlinux-contrib
  - archlinux-wallpaper
  - pacman-contrib
  - man-db
  - man-pages
  - arch-audit
  - xdg-utils
  - libsecret
  - xdg-user-dirs
  - mesa-utils
  - mesa
  - sound-theme-freedesktop
  - nvme-cli
  - flatpak
  - plymouth
  - zram-generator

os_network:
  - iwd
  - networkmanager
  - network-manager-applet

os_audio:
  - pavucontrol
  - pipewire
  - pipewire-audio
  - pipewire-pulse
  - wireplumber
  - gst-plugin-pipewire

common_cmd_util:
  main:
    - fzf
    - eza
    - fd
    - ripgrep
    - bat
    - bat-extras
    - zoxide
    - jq
    - entr
    - htop
    - ffmpeg
    - rsync # file copying tool
    - mpv # Media Player cmd
    - rclone
    - tealdeer # Summarized man pages
    - freerdp # Remote desktop cli
    - yt-x # youtube cmd player
    - 7zip
    - unrar
    - unzip
    - lshw  # list hardware
    - lsof # list open files
    - tree
  aur:
    - lssecret-git
    - tty-clock

common_gui_util:
  main:
    - galculator
    - seahorse
    - font-manager
    - xarchiver # frontend for cli archivers
    - baobab
    - gparted # gui for parted
    - grsync # gui for rsync
    - rhythmbox # music player
    - transmission-gtk # torrent manager
    - remmina # remote desktop
    - atril # pdf reader
    - lxterminal # light terminal emulator
    - gimp # image editor
    - inkscape # svg editor
  aur:
    - distro-grub-themes-arch
    - menulibre
    - plymouth-theme-arch-logo-new
    - grub-customizer
    - localsend-bin # share files local

common_fonts:
  main:
    - ttf-nunito
    - ttf-hack-nerd
    - ttf-iosevka-nerd
    - ttf-firacode-nerd
    - ttf-sourcecodepro-nerd
    - ttf-terminus-nerd
    - ttf-0xproto-nerd
    - ttf-bigblueterminal-nerd
    - otf-codenewroman-nerd
    - ttf-nerd-fonts-symbols
    - woff2-font-awesome
    - noto-fonts-emoji
    - ttf-jetbrains-mono-nerd
  aur:
    - ttf-ms-fonts

thunar_pkgs:
  - gvfs
  - gvfs-smb
  - gvfs-nfs
  - thunar
  - thunar-volman
  - thunar-shares-plugin
  - thunar-archive-plugin
  - thunar-media-tags-plugin

flatpak_pkgs:
  - com.github.johnfactotum.Foliate
  - com.github.maoschanz.drawing
  - com.usebottles.Bottles
  - com.vscodium.codium
  - io.github.flattool.Warehouse
  - com.github.tchx84.Flatseal
  - io.github.flattool.Ignition
  - md.obsidian.Obsidian
  - net.ankiweb.Anki
  - org.gnome.SimpleScan
  - org.openshot.OpenShot
  - org.nickvision.tubeconverter
  - com.protonvpn.www

dev_pkgs:
  main:
    - docker
    - podman
    - lazygit
    - lazydocker
    - toolbox
    - distrobox
    - glib2-devel
  aur:
    - quickemu-git

misc_pkgs:
  main:
    - docker-desktop
    - libreoffice-fresh
    - obs-studio
    - steam
    - android-studio
    - lynis # audit tool CVEs
  amdgpu:
    - radeontop
    - amdgpu_top
  aur:
    - vesktop-bin # discord modified

btrfs_pkgs:
  - snapper
  - snap-pac
  - snapper-rollback
  - btrfs-assistant-git
  - grub-btrfs
