home: "{{ ansible_facts['user_dir'] }}"
config_dir: "{{home}}/.config"
script_dir: "{{home}}/Scripts"

root_dir: "{{playbook_dir}}"
stow_dir: "{{root_dir}}/../"

themes_path:
  - /usr/share/themes
  - "{{home}}/.local/share/themes"
icons_path:
  - /usr/share/icons
  - "{{home}}/.local/share/icons"

default_apps:
  terminal:
    - alacritty
  filemanager:
    - thunar
  browser:
    - brave

thunar_pkgs:
  - gvfs
  - gvfs-smb
  - gvfs-nfs
  - thunar
  - thunar-volman
  - thunar-shares-plugin
  - thunar-archive-plugin
  - thunar-media-tags-plugin

xfce_pkgs:
  - xorg-server
  - xorg-xinit
  - xorg-apps
  - xfce4
  - xfce4-goodies
  - xfce4-panel-profiles
# for tumblerd
  - ffmpegthumbnailer
  - freetype2
  - libgepub
  - libgsf
  - libopenraw
# -------------
  - catfish
  - gigolo
  - mugshot
  - wmctrl
  - redshift
  - geoclue
  - xclip
  - gst-libav
  - conky
  - screenkey
  - xdg-desktop-portal-xapp

wayland_common_pkgs:
  main:
    - swaybg # Background setter
    - swww # animations
    - imv # Image Viewer
    - nwg-look # Theme picker
    - nwg-displays # Display settings
    - nwg-drawer # Big menu
    - nwg-icon-picker # Icon picker
    - wl-clipboard # Clipboard
    - cliphist # Clipboard manager
    - wf-recorder # Screen recorder
    - slurp # Selection area
    - grim # Screenshotter
    - wlsunset # Gamma adjuster
    - xdg-desktop-portal-gtk
    - desktop-file-utils
    - wev
  aur:
    - waypaper # Background setter
    - wvkbd
   # - wallust-git

sway_pkgs:
  - sway
  - swayidle
  - swaylock
  - xdg-desktop-portal-wlr
  - polkit-gnome
  - grimshot

hyprland_pkgs:
  main:
    - hyprland # Wayland compositor
    - hypridle # Idle Manager
    - hyprlock # Lock screen
    - hyprcursor
    - hyprpolkitagent # Polkit agent
    - hyprpicker # Color picker
    - xdg-desktop-portal-hyprland
    - qt5-wayland
    - qt6-wayland
  aur:
    - grimblast-git
   # - hyprsysteminfo-git

xorg_amdgpu:
  - xf86-video-amdgpu

os_intgpu:
  - intel-media-driver

os_essential:
  - archlinux-contrib
  - archlinux-wallpaper
  - pacman-contrib
  - man-db
  - man-pages
  - arch-audit
  - xdg-utils
  - libsecret
  - xdg-user-dirs
  - unrar
  - unzip
  - lshw
  - lsof
  - mesa-utils
  - mesa
  - sound-theme-freedesktop
  - nvme-cli
  - flatpak
  - tree
  - plymouth

os_network:
  - iwd
  - networkmanager
  - network-manager-applet

os_audio:
  - pavucontrol
  - pipewire
  - pipewire-audio
  - pipewire-pulse
  - wireplumber
  - gst-plugin-pipewire

common_cmd_util:
  main:
    - fzf
    - eza
    - fd
    - ripgrep
    - bat
    - bat-extras
    - zoxide
    - jq
    - entr
    - 7zip
    - htop
    - ffmpeg
    - rsync
    - mpv
    - rclone
    - tealdeer
    - freerdp
    - yt-x
  aur:
    - lssecret-git
    - tty-clock

common_gui_util:
  main:
    - galculator
    - seahorse
    - grub-customizer
    - font-manager
    - xarchiver
    - baobab
    - gparted
    - grsync
    - rhythmbox
    - transmission-gtk
    - atril
    - lxterminal
    - gimp # image editor
    - inkscape # svg editor
  aur:
    - distro-grub-themes-arch
    - menulibre
    - plymouth-theme-arch-logo-new
    - grub-customizer
    - localsend-bin # share files local

common_fonts:
  main:
    - ttf-nunito
    - ttf-hack-nerd
    - ttf-iosevka-nerd
    - ttf-firacode-nerd
    - ttf-sourcecodepro-nerd
    - ttf-terminus-nerd
    - ttf-0xproto-nerd
    - ttf-bigblueterminal-nerd
    - otf-codenewroman-nerd
    - ttf-nerd-fonts-symbols
    - woff2-font-awesome
    - noto-fonts-emoji
    - ttf-jetbrains-mono-nerd
  aur:
    - ttf-ms-fonts

flatpak_pkgs:
  - com.github.johnfactotum.Foliate
  - com.github.maoschanz.drawing
  - com.usebottles.Bottles
  - com.vscodium.codium
  - io.github.flattool.Warehouse
  - com.github.tchx84.Flatseal
  - io.github.flattool.Ignition
  - md.obsidian.Obsidian
  - net.ankiweb.Anki
  - org.gnome.SimpleScan
  - org.openshot.OpenShot
  - org.nickvision.tubeconverter
  - org.remmina.Remmina
  - com.protonvpn.www

dev_pkgs:
  main:
    - docker
    - lazygit
    - lazydocker
    - toolbox
    - distrobox
    - glib2-devel
  aur:
    - quickemu-git

misc_pkgs:
  - vesktop-bin # discord modified
  - docker-desktop
  - libreoffice-fresh
  - obs-studio
  - steam
  - android-studio
  - lynis # audit tool CVEs
  - radeontop
  - amdgpu_top
