user_name: "{{ lookup('env', 'USER') }}"
home: "/home/{{user_name}}"
config_dir: "{{home}}/.config"

script_dir: "{{home}}/Scripts"

root_dir: "{{playbook_dir}}"
# home: "{{root_dir}}/test"
# config_dir: "{{root_dir}}/test/config"

themes_path:
  - /usr/share/themes
  - "{{home}}/.local/share/themes"
icons_path:
  - /usr/share/icons
  - "{{home}}/.local/share/icons"

thunar_pkgs:
  - gvfs
  - gvfs-smb
  - gvfs-nfs
  - thunar
  - thunar-volman
  - thunar-shares-plugin
  - thunar-archive-plugin
  - thunar-media-tags-plugin

xfce_pkgs:
  - xorg-server
  - xorg-xinit
  - xorg-apps
  - xfce4
  - xfce4-goodies
  - xfce4-panel-profiles
# for tumblerd
  - ffmpegthumbnailer
  - freetype2
  - libgepub
  - libgsf
  - libopenraw
# -------------
  - catfish
  - gigolo
  - mugshot
  - wmctrl
  - redshift
  - geoclue
  - xclip
  - gst-libav
  - conky
  - screenkey
  - xdg-desktop-portal-xapp

wayland_common_pkgs:
  - swaybg # Background setter
  - waybar # Statusbar
  - swaync # Notification Center
  - swww # animations
  - swaybg # Background setter
  - waypaper # Background setter
  - imv # Image Viewer
  - rofi-wayland # App Launcher
  - nwg-look # Theme picker
  - nwg-displays # Display settings
  - nwg-drawer # Big menu
  - nwg-icon-picker # Icon picker
  - wl-clipboard # Clipboard
  - cliphist # Clipboard manager
  - wf-recorder # Screen recorder
  - slurp # Selection area
  - grim # Screenshotter
  - wlsunset # Gamma adjuster
  - xdg-desktop-portal-gtk
  - desktop-file-utils
  - wev
  - wallust

sway_pkgs:
  - sway
  - swayidle
  - swaylock
  - xdg-desktop-portal-wlr
  - polkit-gnome

hyprland_pkgs:
  - hyprland # Wayland compositor
  - hypridle # Idle Manager
  - hyprlock # Lock screen
  - hyprcursor
  - hyprpolkitagent # Polkit agent
  - hyprpicker # Color picker
  - xdg-desktop-portal-hyprland
  - qt5-wayland
  - qt6-wayland

xorg_amdgpu:
  - xf86-video-amdgpu
os_intgpu:
  - intel-media-driver

os_essential:
  - archlinux-contrib
  - pacman-contrib
  - man-db
  - man-pages
  - arch-audit
  - xdg-utils
  - libsecret
  - xdg-user-dirs
  - unrar
  - unzip
  - lshw
  - lsof
  - mesa-utils
  - mesa
  - sound-theme-freedesktop
  - nvme-cli
  - flatpak
  - tree
  - plymouth

os_network:
  - iwd
  - networkmanager
  - network-manager-applet

os_audio:
  - pavucontrol
  - pipewire
  - pipewire-audio
  - pipewire-pulse
  - wireplumber
  - gst-plugin-pipewire

common_cmd_util:
  - fzf
  - eza
  - fd
  - ripgrep
  - bat
  - bat-extras
  - zoxide
  - jq
  - entr
  - 7zip
  - htop
  - yazi
# yazi optional dependencies
  - poppler
  - imagemagick
  - chafa
  - resvg
# ---------------
  - ffmpeg
  - rsync
  - mpv
  - mpd
  - ncmpcpp
  - zathura
  - zathura-pdf-mupdf
  - rclone
  - fastfetch
  - tealdeer
  - freerdp

common_gui_util:
  - galculator
  - seahorse
  - grub-customizer
  - font-manager
  - xarchiver
  - baobab
  - gparted
  - grsync
  - rhythmbox
  - transmission-gtk
  - atril
  - lxterminal
  - gimp # image editor
  - inkscape # svg editor
  - localsend-bin # share files local

common_fonts:
  - ttf-hack-nerd
  - ttf-iosevka-nerd
  - ttf-firacode-nerd
  - ttf-sourcecodepro-nerd
  - ttf-terminus-nerd
  - ttf-0xproto-nerd
  - ttf-bigblueterminal-nerd
  - otf-codenewroman-nerd
  - ttf-nerd-fonts-symbols
  - woff2-font-awesome
  - noto-fonts-emoji

flatpak_pkgs:
  - com.github.johnfactotum.Foliate
  - com.github.maoschanz.drawing
  - com.usebottles.Bottles
  - com.vscodium.codium
  - io.github.flattool.Warehouse
  - com.github.tchx84.Flatseal
  - io.github.flattool.Ignition
  - md.obsidian.Obsidian
  - net.ankiweb.Anki
  - org.gnome.SimpleScan
  - org.openshot.OpenShot
  - org.nickvision.tubeconverter
  - org.remmina.Remmina
  - com.protonvpn.www

dev_pkgs:
  - podman
  - podman-desktop
  - docker
  - docker-desktop
  - lazygit
  - lazydocker
  - quickemu-git
  - toolbox
  - distrobox
  - radeontop
  - amdgpu_top
  - sshpass # for ansible-core
  - swtpm # for libvirt
# Virtualization/emulation
  - qemu-desktop
  - virt-manager
  - virt-viewer
  - dnsmasq
  - guestfs-tools
  - iptables-nft
# -----------------
  - glib2-devel

dev_misc_pkgs:
  - android-studio
  - lynis # audit tool CVEs

misc_pkgs:
  - vesktop-bin # discord modified
  - libreoffice-fresh
  - obs-studio
  - steam
  - yt-dlp
  - yt-x
