user_name: "{{ lookup('env', 'USER') }}"
home: "/home/{{user_name}}"
config_dir: "{{home}}/.config"

script_dir: "{{home}}/Scripts"

root_dir: "{{playbook_dir}}"
# home: "{{root_dir}}/test"
# config_dir: "{{root_dir}}/test/config"
