- name: Qemu | Installing packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  loop:
    - qemu-desktop
    - virt-manager
    - virt-viewer
    - libosinfo
    - dnsmasq
    - guestfs-tools
    - iptables-nft
    - swtpm
    - edk2-ovmf
  tags: qemu

- name: Qemu | Extra Info
  ansible.builtin.debug:
    msg:
      - "Add the line: 'iommu=pt' if using Amd processor"
      - "or previous one plus 'intel_iommu=on' if using Intel"
  tags: qemu
